project_id = "hzcrlucfyxqxsadbvazi"

[functions.check-ranking]
verify_jwt = false

[functions.check-project-keywords]
verify_jwt = false

[functions.create-sepay-order]
verify_jwt = false

[functions.sepay-webhook]
verify_jwt = false
